#!/bin/sh
set -x

if [ "$1" = "-e" ] ; then
    CMD="cat < /dev/null >"
else
    CMD="rm -f"
fi

# SRP
for f in auth_srp_sb64.c auth_srp_passwd.c auth_srp_rsa.c \
    gnutls_srp.c auth_srp.c ext_srp.c ; do
    eval "$CMD lib/$f"
done

# ECC
for f in ecc.c ; do
    eval "$CMD lib/algorithms/$f"
done
