#!/bin/sh
set -x

if [ "$1" = "-e" ] ; then
    CMD="cat < /dev/null >"
else
    CMD="rm -f"
fi

# SRP
for f in auth_srp_sb64.c auth_srp_passwd.c auth_srp_rsa.c \
    gnutls_srp.c auth_srp.c ext_srp.c ; do
    eval "$CMD lib/$f"
done

# ECC
for f in ecc_free.c ecc_make_key.c ecc_shared_secret.c \
    ecc_map.c ecc_mulmod.c ecc_mulmod_cached.c \
    ecc_points.c ecc_projective_dbl_point_3.c ecc_projective_isneutral.c \
    ecc_projective_check_point.c ecc_projective_negate_point.c \
    ecc_projective_add_point_ng.c ecc_sign_hash.c ecc_verify_hash.c ; do
    eval "$CMD lib/nettle/$f"
done
